version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [deps, ci]

  - package-ecosystem: pip
    directory: "/apps/api"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [deps, api]

  - package-ecosystem: pip
    directory: "/apps/ml"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [deps, ml]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: [deps, web]

  - package-ecosystem: pub
    directory: "/apps/mobile"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [deps, mobile]
